### ISSUE TITLE
Burst is Python-based, but README doesn't say that anywhere.

### ISSUE THREAD

**Issue by kfogel** [tweksteen/burst#10]
Burst is apparently an HTTP framework *for Python*, but the `README.md` doesn't actually state the programming language anywhere.  It might be useful to mention the language.

**Comment by denisinla** [comment]
+1

**Comment by tweksteen** [comment]
Hi there,

Thank you for this comment. Unfortunately, I don't think this is necessary. I have some pro tips for you next time you need to quickly discover the programming language of a project:

 * In the main directory, just next to the concise README, there is a "setup.py" file. Although the .py may refer to the [Paraguay TLD](http://en.wikipedia.org/wiki/.py), it is also the usual extension for Python files.

* A bit further up, just under the number of commits, GitHub provides a [Language Stats Bar](https://github.com/github/linguist). If you click on the colour (a deep blue in our case), statistics on the languages used will be displayed. For Burst, it is  Python 99.5%.

* If you still have any doubt at that stage, you could clone the repository and run a tool such as sloccount. Here is the output of this program on master:


        %SLOC    Directory       SLOC-by-Language (Sorted)
        2728    burst           python=2728
        27      bin             sh=18,python=9
        20      top_dir         python=20
        Totals grouped by language (dominant language first):
        python:        2757 (99.35%)
        sh:              18 (0.65%)


Sincerely,
